create table TASK
(
    id                       bigint unsigned     not null primary key,
    guid                     varchar(255)        character set utf8 collate utf8_bin not null,
    added                    timestamp           not null default 0,
    updated                  timestamp           not null default 0,
    owner_id                 bigint unsigned     not null,
    added_by_uri_path_id     bigint unsigned     not null,
    added_by_uri_ref         varchar(256)        character set latin1 collate latin1_general_cs not null,
    updated_by_uri_path_id   bigint unsigned     not null,
    updated_by_uri_ref       varchar(256)        character set latin1 collate latin1_general_cs not null,
    version                  bigint unsigned     not null,
    locked                   bit                 not null,
    title                    varchar(64)         character set utf8 collate utf8_general_ci not null,
    description              text                character set utf8 collate utf8_general_ci not null,

    task_type                varchar(64)         character set utf8 collate utf8_general_ci not null,
    task_type_revision       varchar(32)         character set utf8 collate utf8_general_ci not null,
    task_message             mediumtext          character set utf8 collate utf8_general_ci not null,
    task_result              mediumtext          character set utf8 collate utf8_general_ci not null,
    priority                 tinyint unsigned    not null,
    processing_agent_id      bigint unsigned     not null,
    required_agent_id        bigint unsigned     not null,
    requires_post_processing bit                 not null,
    status_enum              tinyint             not null,
    percent_complete         decimal(5, 2)       not null,
    maximum_attempts         tinyint unsigned    not null,
    attempt_number           tinyint unsigned    not null,
    batch_id                 bigint unsigned     null,
    task_type_id             bigint unsigned     not null,
    task_template_id         bigint unsigned     null,
    parent_account_id        bigint unsigned     not null,

	unique index UX_TASK_GUID (guid, owner_id),
    index IX_TASK_TITLE (title),
    -- index IX_TASK_ADDED (added),  -- temp remove (seemed to make getNextTask worse?)
    index IX_TASK_UPDATED (updated),
    index IX_TASK_TASK_TYPE (task_type_id),
    index IX_TASK_STATUS (status_enum),
    index IX_TASK_BATCH_ID (batch_id),
    index IX_TASK_NEXT_TASK_NO_FAIR (processing_agent_id,priority, added),
    index IX_TASK_NEXT_TASK_1 (processing_agent_id,added),
    index IX_TASK_NEXT_TASK_2 (owner_id,processing_agent_id,priority,added),
    index IX_TASK_OWNER_STATUS (owner_id, status_enum),
    index IX_TASK_OWNER_TASK_TYPE (owner_id,task_type,status_enum),
    index IX_TASK_OWNER_UPDATED (owner_id, updated),
    constraint FK_TASK_BATCH    foreign key IX_TASK_BATCH_ID (batch_id)            references BATCH (id),
    constraint FK_TASK_TEMPLATE foreign key IX_TASK_TEMPLATE_ID (task_template_id) references TASK_TEMPLATE (id),
    constraint FK_TASK_TYPE     foreign key IX_TASK_TYPE_ID (task_type_id)         references TASK_TYPE_DEFINITION (id)
) engine = InnoDB;