agendaProviderUrl: ''
identityUrl: ''
username: ''
encryptedPassword: ''

agendaRequestCount: 1
pullWait: 10
insightId: '599f2241-3877-4301-b3d2-aa7e4274e421'

localAgendaRelativePath: '/Agenda.json'
#logging:
#  level: INFO
#  loggers:
#    org.eclipse.jetty: WARN
#    io.dropwizard: WARN
#    org.apache.http: WARN
#    io.fabric8.kubernetes.client.Config: WARN