apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cppull
  name: pop-puller-01
  namespace: pop
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: cppull
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cppull
      name: pop-puller-01
      namespace: pop
    spec:
      containers:
      - env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: cppull:1.0.0
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 25
        name: cppull
        ports:
        - containerPort: 8081
          name: admin
          protocol: TCP
        - containerPort: 8080
          name: service
          protocol: TCP
        resources:
          limits:
            memory: 1G
          requests:
            cpu: 250m
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config
          name: config-volume
        - mountPath: /dumps
          name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pop-service
      serviceAccountName: pop-service
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: env-properties
            path: env.properties
          - key: external-properties
            path: external.properties
          - key: conf-yaml
            path: conf.yaml
          - key: registry-json
            path: registry.json
          name: pop-puller-01
        name: config-volume
      - emptyDir: {}
        name: log
