agendaProviderUrl: 'https://iqeyna6qnd.execute-api.us-west-2.amazonaws.com/dev/dfh/idm/service/agendaprovider'
identityUrl: 'http://identity.auth.test.corp.theplatform.com/idm'
username: 'service/dfh.filehandler.user.dev1@theplatform.com'
encryptedPassword: 'iVcsBRR0FPee/pgnFI+mAw=='
pullWait: 10
insightId:
agendaRequestCount: 1
logging:
  level: INFO
  loggers:
    org.eclipse.jetty: WARN
    io.dropwizard: WARN
    org.apache.http: WARN
    io.fabric8.kubernetes.client.Config: WARN